// frontend/src/App.svelte
<script lang='typescript'>
    import {onMount} from 'svelte';
    import {AutoAPI} from 'autoapi-client'

    const autoAPI = new AutoAPI("http://localhost:8081")
    autoAPI

    let count: number = 0;
    onMount(() => {
        const interval = setInterval(() => count++, 1000);
        return () => {
            clearInterval(interval);
        };
    });
</script>

<style>
    :global(body) {
        margin: 0;
        font-family: Arial, Helvetica, sans-serif;
    }
    .App {
        text-align: center;
    }
    .App code {
        background: #0002;
        padding: 4px 8px;
        border-radius: 4px;
    }
    .App p {
        margin: 0.4rem;
    }

    .App-header {
        background-color: #f9f6f6;
        color: #333;
        min-height: 100vh;
        display: flex;
        flex-direction: column;
        align-items: center;
        justify-content: center;
        font-size: calc(10px + 2vmin);
    }
    .App-link {
        color: #ff3e00;
    }
    .App-logo {
        height: 36vmin;
        pointer-events: none;
        margin-bottom: 3rem;
        animation: App-logo-spin infinite 1.6s ease-in-out alternate;
    }
    @keyframes App-logo-spin {
        from {
            transform: scale(1);
        }
        to {
            transform: scale(1.06);
        }
    }
</style>

<div class="App">
    <header class="App-header">
        <img src="/logo.svg" class="App-logo" alt="logo" />
        <p>Edit <code>src/App.svelte</code> and save to reload.</p>
        <p>Page has been open for <code>{count}</code> seconds.</p>
        <p>
            <a class="App-link" href="https://svelte.dev" target="_blank" rel="noopener noreferrer">
                Learn Svelte
            </a>
        </p>
    </header>
</div>

// react-frontend/src/App.tsx
import logo from './logo.svg';
import './App.css';
import {AutoAPI} from 'autoapi-client'
import {SampleResponse} from 'autoapi-shared'
import {useEffect} from "react";

function App() {
    const client = new AutoAPI("http://localhost:8080");

    useEffect(() => {
        client.getRestaurants()
            .then((result: SampleResponse) => console.log(result))
            .catch((error: any) => console.error(error))
    })

    return (
        <div className="App">
            <header className="App-header">
                <img src={logo} className="App-logo" alt="logo"/>
                <p>
                    Edit <code>src/App.js</code> and save to reload.
                </p>
                <a
                    className="App-link"
                    href="https://reactjs.org"
                    target="_blank"
                    rel="noopener noreferrer"
                >
                    Learn React
                </a>
            </header>
        </div>
    );
}

export default App;
